### ISSUE TITLE
Audit logs have wrong POSIX/Unix timestamp

### ISSUE THREAD

**Issue by vikoivun** [City-of-Helsinki/open-city-profile#263]
https://github.com/City-of-Helsinki/open-city-profile/blob/37ea0d9c282856a1099e0008badbc557771ea4a4/profiles/log_signals.py#L39-L50

Calling timestamp() on non-timezone ("naive") datetime interprets the datetime object as being in local time. And Django is hardcoded to "Europe/Helsinki" in settings.py. Meaning that the generated timestamp is either two or three hours in the wrong, depending on whether that timezone is observing daylight saving currently.

I'd say the best fix would be follow the advice in [Python docs](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) and attach timezone to `current_time`.
This will need changes to isoformat, as it will want to append `+00:00` to output otherwise.

**Comment by akikoskinen** [comment]
I'll handle this.

**Comment by akikoskinen** [comment]
Fixed in 35d7218ee1 and efc1958ba9.
