### ISSUE TITLE
Migrate OIDC API token auth related settings to use new naming

### ISSUE THREAD

**Issue by tuomas777** [City-of-Helsinki/open-city-profile#31]
New names:

TOKEN_AUTH_ACCEPTED_AUDIENCE
TOKEN_AUTH_FIELD_FOR_CONSENTS
TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX
TOKEN_AUTH_REQUIRE_SCOPE_PREFIX
TOKEN_AUTH_AUTHSERVER_URL

**Comment by klempine** [comment]
Is this still a valid issue or should we just close this?
